[package]
name = "abi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "load"
path = "src/main.rs"

[dependencies]
impls = { path = "../impls" }
libloading = "0.8.5"
once_cell = "1.19.0"
